package org.jgeek.website.model.security;

import javax.persistence.*;
import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * create table groups
 * (
 * id bigint generated by default as identity(start with 0) primary key,
 * group_name varchar_ignorecase(50) not null
 * );
 * <p/>
 * User: Dmitry Leontyev
 * Date: 26.12.10
 * Time: 23:41
 */
@Entity
@Table(name = "USER_GROUP")
public class UserGroup implements Serializable {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @Column(length = 50, nullable = false, unique = true)
    private String groupName;

    @OneToMany(cascade = CascadeType.ALL)
    @JoinTable(name = "GROUP_AUTHORITY")
    private Set<UserAuthority> authorities = new HashSet<UserAuthority>();

    @ManyToMany(mappedBy = "groups", cascade = CascadeType.ALL)
    private Set<UserAccount> accounts = new HashSet<UserAccount>();

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getGroupName() {
        return groupName;
    }

    public void setGroupName(String groupName) {
        this.groupName = groupName;
    }

    public Set<UserAuthority> getAuthorities() {
        return authorities;
    }

    public void setAuthorities(Set<UserAuthority> authorities) {
        this.authorities = authorities;
    }

    public Set<UserAccount> getAccounts() {
        return accounts;
    }

    public void setAccounts(Set<UserAccount> accounts) {
        this.accounts = accounts;
    }
}
